### ISSUE TITLE
Issue running the Chrome Implementation

### ISSUE THREAD

**Issue by tplooker** [WICG/WebID#53] opened 2020-12-16 01:32 UTC
Hi, I've tried to test out the API in Chrome 89 (running version 89.0.4356.0) as per the [how to guide](https://github.com/WICG/WebID/blob/master/HOWTO.md) and I've encountered an issue where I am getting [this DOMException "Error loading the identity provider"](https://chromium.googlesource.com/chromium/src/+/ae72289872efe931fc54f3f7555ede116b4638ce/third_party/blink/renderer/modules/webid/web_id.cc#28). [Here](https://github.com/tplooker/webid-playground) is the little POC I was running to test, I can see the browser is making the request to the well-known endpoint but it then throws this exception before rendering any native UI, obviously the implementation of the IDP is incomplete but I cannot see why it would be throwing this exception.

**Comment by kenrb** [comment] 2020-12-16 15:16
Thanks for trying this out. One of the things I am working on is adding more descriptive console messages and also connecting our network requests to dev tools to make this easier to diagnose problems. The error either means that the request is receiving other than HTTP 200 back from the server, or else the JSON isn't parsing correctly.

One problem we learned about recently is that if the test IDP is hosted on a server that requires cookies (which is common on private infrastructure), the `/.well-known/WebID` request will fail, because that is deliberately sent uncredentialed. We are looking at how to make that easier.

**Comment by timcappalli** [comment] 2020-12-17 02:34
I'm also seeing this. My response looks properly formed.

http https://myidp.removed:7100/.well-known/webid
`
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 75
Content-Type: application/json; charset=utf-8
Date: Thu, 17 Dec 2020 02:32:59 GMT
ETag: W/"4b-KKt7uopx4l7XkR/Hgo9hRsYMisI"
Keep-Alive: timeout=5
Set-Cookie: connect.sid=s%3AyUW7Wilg5eclQLiYKBylwY6P0-k0elfV.d5YSJhGfJ6JYi%2FucTEo73fjbB0Hu%2B4mEN69uZ3AP%2BYw; Path=/; HttpOnly
X-Powered-By: Express

{
    "idp_endpoint": "https://myidp.removed:7100/webid/signin"
}
`

**Comment by timcappalli** [comment] 2020-12-31 02:45
navigator.id does not seem to be available in the latest build.

![image](https://user-images.githubusercontent.com/6476604/103391618-5abaed00-4ae8-11eb-8eea-4aaa7703cd6f.png)

![image](https://user-images.githubusercontent.com/6476604/103391573-2c3d1200-4ae8-11eb-9139-0b8cb1bed661.png)

**Comment by timcappalli** [comment] 2021-01-14 15:01
Confirmed that this specific issue is fixed as of 2021-01-14

**Comment by kenrb** [comment] 2021-01-14 16:19
Thanks for verifying, @timcappalli. I'll mention that the prototype is still very early, as so far we are trying to work out any questions around data flows.

**Closed by kenrb** 2021-01-14 16:19 UTC
